
en:
  languageCode: en-us
  contentDir: content/en
  title: English Website Title
  params:
    description: Site description in English...

pl:
  languageCode: pl-pl
  contentDir: content/pl
  title: Polish Website Title
  params:
    description: Opis strony po polsku...
