
# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en

# Additional language
es:
  languageCode: es-es
  contentDir: content/es
  title: Spanish Site Title
  params:
    description: Sitio web en español.
